"""Risk alert Pydantic data models."""

from datetime import datetime
from enum import Enum

from pydantic import BaseModel


class Severity(str, Enum):
    """Alert severity levels."""

    LOW = "low"
    MEDIUM = "medium"
    HIGH = "high"


class RiskAlert(BaseModel):
    """A risk alert generated by the disruption detector."""

    id: str
    shipment_id: str
    severity: Severity
    title: str
    description: str
    created_at: datetime
    is_active: bool = True
